'use client'
import { useEffect } from 'react'
import './assets/css/animate.min.css'
import './assets/css/style.css'
import AOS from 'aos'
import Header from './components/common/Header'
import Footer from './components/common/Footer'
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    AOS.init({ duration: 1000 }) // Animation duration in ms
  }, [])
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
